"""Database migration

Revision ID: 04e15efdd3b8
Revises: 
Create Date: 2024-08-28 00:12:48.958293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e15efdd3b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        '__user__',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hash_password', sa.String(), nullable=False),
        sa.Column('registr_time', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###alembic


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('__user__')
    # ### end Alembic commands ###
