"""Database migration users

Revision ID: b962508170f7
Revises: 04e15efdd3b8
Create Date: 2024-08-28 02:28:43.464223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b962508170f7'
down_revision: Union[str, None] = '04e15efdd3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('__user__', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('__user__', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('__user__', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('__user__', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('__user__', 'hash_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('__user__', sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('__user__', 'is_verified')
    op.drop_column('__user__', 'is_superuser')
    op.drop_column('__user__', 'is_active')
    op.drop_column('__user__', 'hashed_password')
    # ### end Alembic commands ###
